# Site Settings
title: Start Jekyll
email: arvind@cheenu.net
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "http://thebicameralbit.github.io"
twitter_username: arvindcheenu12
github_username:  arvindcheenu
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM